### ISSUE TITLE
Explore the Coursera API from the network tab in browser developer tools

### ISSUE THREAD

**Issue by gridhead** [schezfaz/3.0.2#11]
As Karan Sheth remarked, the API endpoints would be visible from the network tab in the browser's developer tools and that would not be needing any API keys to make it function.

This would need some investigating before actually getting down to its implementation.

**Comment by Bentheburrito** [comment]
Udemy just approved the API client! We might not have to do this after all :) I can work on integrating both edX and Udemy APIs today

**Comment by abishekvashok** [comment]
Awesome news @Bentheburrito
