### ISSUE TITLE
Fetch information about course catalog from Coursera

### ISSUE THREAD

**Issue by gridhead** [schezfaz/3.0.2#5]
This resource can be utilized in order to fetch catalog information remotely https://course-catalog-api-guide.readthedocs.io/en/latest/intro_edx_apis.html and https://build.coursera.org/app-platform/catalog/#:~:text=The%20Catalog%20APIs%20expose%20the,without%20authentication%20over%20the%20internet

**Comment by Bentheburrito** [comment]
Hi all,

I did some digging into Coursera's APIs earlier today and it doesn't seem like they offer course prices as apart of either the [Catalog API](https://build.coursera.org/app-platform/catalog/) or the [OAuth2 APIs](https://build.coursera.org/app-platform/oauth2/) (feel free to double check me on this though). I found a pretty detailed article on [Coursera's pricing policies](https://upskillwise.com/coursera-cost/) that includes specific ranges, so worst case we can use those?

As a potential alternative, I looked at Udemy, and it looks like they do offer [course prices](https://www.udemy.com/developers/affiliate/models/course/) as an option. I applied for an API Client earlier this afternoon, though I guess it's not an automatically-granted thing, as I applied ~8 hours ago and it's still "Pending"...and this [Reddit comment](https://www.reddit.com/r/Udemy/comments/hxesxe/is_anyone_actually_able_to_request_an_affiliate/g5luuy8?utm_source=share&utm_medium=web2x&context=3) (unfortunately) indicates it might not even be looked at

What do you all think? Does anyone know of any more educational sites with APIs like the above? @t0xic0der @abishekvashok @schezfaz

**Comment by Bentheburrito** [comment]
We can also of course discuss this in the meeting today. :)

**Comment by abishekvashok** [comment]
It was decided that we stall this for now, since we require an API key and focus on YouTube playlists #6 and edX #2 instead.
