### ISSUE TITLE
Implement YouTube API for free courses and their comparison

### ISSUE THREAD

**Issue by gridhead** [schezfaz/3.0.2#6]
There is a plethora of free courses on YouTube which should be included in the comparison.

**Comment by abishekvashok** [comment]
Here's a YouTube playlist API: https://developers.google.com/youtube/v3/docs/playlists/list
And there's a module called yt-search that doesn't require auth keys!

**Comment by abishekvashok** [comment]
Since, we have a public api available to search for playlists about courses, lets include that in v1.0
