### ISSUE TITLE
Build on the frontend with the help of Stylex

### ISSUE THREAD

**Issue by gridhead** [schezfaz/3.0.2#7]
Plain CSS/JS/HTML to be used in building the frontend with the integration with Stylex

**Comment by schezfaz** [comment]
After watching the Facebook conf talk on [Stylex](https://www.youtube.com/watch?v=9JZHodNR184&t=229s),  and going through its documentation - I believe it would be easier to configure this library with a React frontend.

Currently, we are templating the frontend using the jade engine - and I'm not too sure on how we can go about integrating the two together i.e. Stylex + Jade.

I'd like to propose shifting to a React frontend. I understand that majority of us are not very familiar with it, however being fairly familiar with it myself I'd be down to give a brief overview about the same. Either that, or we could spend some time and figure how to go about incoorporating Stylex with basic html or the templating engine. 

Thoughts? @Bentheburrito @t0xic0der @abishekvashok

**Comment by abishekvashok** [comment]
@schezfaz so I watched the talk you mentioned, and it seems reactJS would be an `easier option to integrate stylex`. I don't know much of react, but I will be happy to  assist with the frontend after an initial version is up. What are your thoughts @t0xic0der @Bentheburrito

**Comment by schezfaz** [comment]
Yes, true! Sounds good. Are we going with this? If so, we might need to do a little restructuring as per [this article](https://www.freecodecamp.org/news/create-a-react-frontend-a-node-express-backend-and-connect-them-together-c5798926047c/). Let's figure on call today!

**Comment by Bentheburrito** [comment]
I'm down for this! Wouldn't mind learning some React and helping out in the front end side of things

**Comment by abishekvashok** [comment]
ya count me in as well!
